### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by alehano** [imotov/elasticsearch-analysis-morphology#24] opened 2015-11-01 15:23 UTC
Hi. Thanks for plugin.

When will be release for 2.0.0?

Get this error now:
```
ERROR: Plugin [elasticsearch-analysis-morphology] is incompatible with Elasticsearch [2.0.0]. Was designed for version [2.0.0-beta1]
```

**Comment by imotov** [comment] 2015-11-02 12:24
Duplicate of #23

**Closed by imotov** 2015-11-02 12:24 UTC

**Comment by alehano** [comment] 2015-11-02 15:30
Thanks!!!
