### ISSUE TITLE
elasticsearch-analysis-morphology-5.6.16.zip not found

### ISSUE THREAD

**Issue by web-premier** [imotov/elasticsearch-analysis-morphology#65] opened 2021-06-14 12:08 UTC
Hello!
I have error when download plugin by link http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.16/elasticsearch-analysis-morphology-5.6.16.zip
Where I can get it?

**Comment by imotov** [comment] 2021-06-15 01:21
Duplicate of #64

**Closed by imotov** 2021-06-15 01:21 UTC

**Comment by imotov** [comment] 2021-06-15 02:17
I have updated the readme with the building from source instructions.
